context:
  name: essimaging
  version: "25.8.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essimaging-${{ version }}.tar.gz
  sha256: 949cb816ecce2d79082cd4901860cacfebbcaa835a2ec8f3d3991a3430f6749f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core >=2022.1.0
    - python-graphviz
    - plopp >=23.10.0
    - sciline >=23.9.1
    - scipp >=23.8.0
    - scippneutron >=24.12.0
    - scippnexus >=23.11.1
    - essreduce >=25.07.0
    - tifffile >=2024.7.2

tests:
  - python:
      imports:
        - ess.imaging
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Imaging data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/essimaging
  homepage: https://scipp.github.io/essimaging/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
