context:
  name: essimaging
  version: "26.9.1"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essimaging-${{ version }}.tar.gz
  sha256: 48efaea1b769c361508a9a00ebc52765360818669a13de9744c17e4a4e51a374

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - dask-core >=2022.1.0
    - python-graphviz
    - plopp >=23.10.0
    - tifffile >=2026.5.2
    - essreduce >=26.6.2
    - scitiff >=26.6

tests:
  - python:
      imports:
        - ess.imaging
      python_version:
        - ${{ python_min }}.*
        - "*"
about:
  summary: Imaging data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/ess/tree/main/packages/essimaging
  homepage: https://scipp.github.io/ess/imaging/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
